<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.9.4"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>My Project: CException &lt;img src=&quot;https://github.com/ThrowTheSwitch/CException/workflows/CI/badge.svg&quot; alt=&quot;CI&quot;/&gt;</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="doxygen-awesome.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">My Project
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.4 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
var searchBox = new SearchBox("searchBox", "search",'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(document).ready(function(){initNavTree('md_lib_CException_README.html',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div><div class="header">
  <div class="headertitle"><div class="title">CException <img src="https://github.com/ThrowTheSwitch/CException/workflows/CI/badge.svg" alt="CI" style="pointer-events: none;" class="inline"/> </div></div>
</div><!--header-->
<div class="contents">
<div class="textblock"><p ><em>This Documentation Is Released Under a Creative Commons 3.0 Attribution Share-Alike License</em></p>
<p >CException is simple exception handling in C. It is significantly faster than full-blown C++ exception handling but loses some flexibility. It is portable to any platform supporting <code>setjmp</code>/<code>longjmp</code>.</p>
<h1><a class="anchor" id="autotoc_md29"></a>
Getting Started</h1>
<p >The simplest way to get started is to just grab the code and pull it into your project:</p>
<div class="fragment"><div class="line">git clone https://github.com/throwtheswitch/cexception.git</div>
</div><!-- fragment --><p >If you want to contribute to this project, you'll also need to have Ruby and Ceedling installed to run the unit tests.</p>
<h1><a class="anchor" id="autotoc_md30"></a>
Usage</h1>
<h3><a class="anchor" id="autotoc_md31"></a>
So what's it good for?</h3>
<p >Mostly error handling. Passing errors down a long chain of function calls gets ugly. Sometimes really ugly. So what if you could just specify certain places where you want to handle errors, and all your errors were transferred there? Let's try a lame example:</p>
<p >CException uses C standard library functions setjmp and longjmp to operate. As long as the target system has these two functions defined, this library should be useable with very little configuration. It even supports environments where multiple program flows are in use, such as real-time operating systems... we started this project for use in embedded systems... but it obviously can be used for larger systems too.</p>
<h3><a class="anchor" id="autotoc_md32"></a>
Error Handling with CException:</h3>
<div class="fragment"><div class="line">void functionC(void) {</div>
<div class="line">  //do some stuff</div>
<div class="line">  if (there_was_a_problem)</div>
<div class="line">    Throw(ERR_BAD_BREATH);</div>
<div class="line">  //this stuff never gets called because of error</div>
<div class="line">}</div>
</div><!-- fragment --><p >There are about a gajillion exception frameworks using a similar setjmp/longjmp method out there... and there will probably be more in the future. Unfortunately, when we started our last embedded project, all those that existed either (a) did not support multiple tasks (therefore multiple stacks) or (b) were way more complex than we really wanted. CException was born.</p>
<h1><a class="anchor" id="autotoc_md33"></a>
Why?</h1>
<h3><a class="anchor" id="autotoc_md34"></a>
It's ANSI C</h3>
<p >...and it beats passing error codes around.</p>
<h3><a class="anchor" id="autotoc_md35"></a>
You want something simple...</h3>
<p >CException throws a single id. You can define those ID's to be whatever you like. You might even choose which type that number is for your project. But that's as far as it goes. We weren't interested in passing objects or structs or strings... just simple error codes. Fast. Easy to Use. Easy to Understand.</p>
<h3><a class="anchor" id="autotoc_md36"></a>
Performance...</h3>
<p >CException can be configured for single tasking or multitasking. In single tasking, there is very little overhead past the setjmp/longjmp calls (which are already fast). In multitasking, your only additional overhead is the time it takes you to determine a unique task id (0 to num_tasks).</p>
<h1><a class="anchor" id="autotoc_md37"></a>
How?</h1>
<p >Code that is to be protected are wrapped in <code>Try { }</code> blocks. The code inside the Try block is <em>protected</em>, meaning that if any Throws occur, program control is directly transferred to the start of the Catch block. The Catch block immediately follows the Try block. It's ignored if no errors have occurred.</p>
<p >A numerical exception ID is included with Throw, and is passed into the Catch block. This allows you to handle errors differently or to report which error has occurred... or maybe it just makes debugging easier so you know where the problem was Thrown.</p>
<p >Throws can occur from anywhere inside the Try block, directly in the function you're testing or even within function calls (nested as deeply as you like). There can be as many Throws as you like, just remember that execution of the guts of your Try block ends as soon as the first Throw is triggered. Once you throw, you're transferred to the Catch block. A silly example:</p>
<div class="fragment"><div class="line">void SillyExampleWhichPrintsZeroThroughFive(void) {</div>
<div class="line">  volatile CEXCEPTION_T e;</div>
<div class="line">  int i;</div>
<div class="line">  while (i = 0; i &lt; 6; i++) {</div>
<div class="line">    Try {</div>
<div class="line">      Throw(i);</div>
<div class="line">      //This spot is never reached</div>
<div class="line">    } </div>
<div class="line">    Catch(e) {</div>
<div class="line">      printf(“%i “, e);</div>
<div class="line">    }</div>
<div class="line">  }</div>
<div class="line">}</div>
</div><!-- fragment --><h1><a class="anchor" id="autotoc_md38"></a>
Limitations</h1>
<p >This library was made to be as fast as possible, and provide basic exception handling. It is not a full-blown exception library like C++. Because of this, there are a few limitations that should be observed in order to successfully utilize this library:</p>
<h3><a class="anchor" id="autotoc_md39"></a>
Return &amp; Goto</h3>
<p >Do not directly <code>return</code> from within a <code>Try</code> block, nor <code>goto</code> into or out of a <code>Try</code> block. The <code>Try</code> macro allocates some local memory and alters a global pointer. These are cleaned up at the top of the <code>Catch</code> macro. Gotos and returns would bypass some of these steps, resulting in memory leaks or unpredictable behavior.</p>
<h3><a class="anchor" id="autotoc_md40"></a>
Local Variables</h3>
<p >If (a) you change local (stack) variables within your <code>Try</code> block, and (b) wish to make use of the updated values after an exception is thrown, those variables should be made <code>volatile</code>.</p>
<p >Note that this is ONLY for locals and ONLY when you need access to them after a <code>Throw</code>.</p>
<p >Compilers optimize (and thank goodness they do). There is no way to guarantee that the actual memory location was updated and not just a register unless the variable is marked volatile.</p>
<h3><a class="anchor" id="autotoc_md41"></a>
Memory Management</h3>
<p >Memory which is <code>malloc</code>'d within a <code>Try</code> block is not automatically released when an error is thrown. This will sometimes be desirable, and other times may not. It will be the responsibility of the code you put in the <code>Catch</code> block to perform this kind of cleanup.</p>
<p >There's just no easy way to track <code>malloc</code>'d memory, etc., without replacing or wrapping <code>malloc</code> calls or something like that. This is a lightweight framework, so these options were not desirable.</p>
<h1><a class="anchor" id="autotoc_md42"></a>
CException API</h1>
<h3><a class="anchor" id="autotoc_md43"></a>
&lt;tt&gt;Try { ... }&lt;/tt&gt;</h3>
<p ><code>Try</code> is a macro which starts a protected block. It MUST be followed by a pair of braces or a single protected line (similar to an 'if'), enclosing the data that is to be protected. It MUST be followed by a <code>Catch</code> block (don't worry, you'll get compiler errors to let you know if you mess any of that up).</p>
<p >The <code>Try</code> block is your protected block. It contains your main program flow, where you can ignore errors (other than a quick <code>Throw</code> call). You may nest multiple <code>Try</code> blocks if you want to handle errors at multiple levels, and you can even rethrow an error from within a nested <code>Catch</code>.</p>
<h3><a class="anchor" id="autotoc_md44"></a>
&lt;tt&gt;Catch(e) { }&lt;/tt&gt;</h3>
<p ><code>Catch</code> is a macro which ends the <code>Try</code> block and starts the error handling block. The <code>Catch</code> block is executed if and only if an exception was thrown while within the <code>Try</code> block. This error was thrown by a <code>Throw</code> call somewhere within <code>Try</code> (or within a function called within <code>Try</code>, or a function called by a function called within <code>Try</code>... you get the idea.).</p>
<p ><code>Catch</code> receives a single id of type <code>CEXCEPTION_T</code> which you can ignore or use to handle the error in some way. You may throw errors from within Catches, but they will be caught by a <code>Try</code> wrapping the <code>Catch</code>, not the one immediately preceeding.</p>
<h3><a class="anchor" id="autotoc_md45"></a>
&lt;tt&gt;Throw(e)&lt;/tt&gt;</h3>
<p ><code>Throw</code> is the method used to throw an error. <code>Throw</code>s should only occur from within a protected (<code>Try</code>...<code>Catch</code>) block, though it may easily be nested many function calls deep without an impact on performance or functionality. <code>Throw</code> takes a single argument, which is an exception id which will be passed to <code>Catch</code> as the reason for the error. If you wish to <em>re-throw</em> an error, this can be done by calling <code>Throw(e)</code> with the error code you just caught. It <em>IS</em> valid to throw from a <code>Catch</code> block.</p>
<h3><a class="anchor" id="autotoc_md46"></a>
&lt;tt&gt;ExitTry()&lt;/tt&gt;</h3>
<p ><code>ExitTry</code> is a method used to immediately exit your current Try block but NOT treat this as an error. Don't run the Catch. Just start executing from after the Catch as if nothing had happened.</p>
<h1><a class="anchor" id="autotoc_md47"></a>
Configuration</h1>
<p >CException is a mostly portable library. It has one universal dependency, plus some macros which are required if working in a multi-tasking environment.</p>
<p >The standard C library setjmp must be available. Since this is part of the standard library, it's all good.</p>
<p >If working in a multitasking environment, you need a stack frame for each task. Therefore, you must define methods for obtaining an index into an array of frames and to get the overall number of id's are required. If the OS supports a method to retrieve task ID's, and those tasks are number 0, 1, 2... you are in an ideal situation. Otherwise, a more creative mapping function may be required. Note that this function is likely to be called twice for each protected block and once during a throw. This is the only added overhead in the system.</p>
<p >You have options for configuring the library, if the defaults aren't good enough for you. You can add defines at the command prompt directly. You can always include a configuration file before including <code><a class="el" href="CException_8h_source.html">CException.h</a></code>. You can make sure <code>CEXCEPTION_USE_CONFIG_FILE</code> is defined, which will force make CException look for <code><a class="el" href="CExceptionConfig_8h_source.html">CExceptionConfig.h</a></code>, where you can define whatever you like. However you do it, you can override any or all of the following:</p>
<h3><a class="anchor" id="autotoc_md48"></a>
&lt;tt&gt;CEXCEPTION_T&lt;/tt&gt;</h3>
<p >Set this to the type you want your exception id's to be. Defaults to an 'unsigned int'.</p>
<h3><a class="anchor" id="autotoc_md49"></a>
&lt;tt&gt;CEXCEPTION_NONE&lt;/tt&gt;</h3>
<p >Set this to a number which will never be an exception id in your system. Defaults to <code>0x5a5a5a5a</code>.</p>
<h3><a class="anchor" id="autotoc_md50"></a>
&lt;tt&gt;CEXCEPTION_GET_ID&lt;/tt&gt;</h3>
<p >If in a multi-tasking environment, this should be set to be a call to the function described in #2 above. It defaults to just return 0 all the time (good for single tasking environments, not so good otherwise).</p>
<h3><a class="anchor" id="autotoc_md51"></a>
&lt;tt&gt;CEXCEPTION_NUM_ID&lt;/tt&gt;</h3>
<p >If in a multi-tasking environment, this should be set to the number of ID's required (usually the number of tasks in the system). Defaults to 1 (good for single tasking environments or systems where you will only use this from one task).</p>
<h3><a class="anchor" id="autotoc_md52"></a>
&lt;tt&gt;CEXCEPTION_NO_CATCH_HANDLER (id)&lt;/tt&gt;</h3>
<p >This macro can be optionally specified. It allows you to specify code to be called when a Throw is made outside of Try...Catch protection. Consider this the emergency fallback plan for when something has gone terribly wrong.</p>
<h3><a class="anchor" id="autotoc_md53"></a>
And More!</h3>
<p >You may also want to include any header files which will commonly be needed by the rest of your application where it uses exception handling here. For example, OS header files or exception codes would be useful.</p>
<p >Finally, there are some hook macros which you can implement to inject your own target-specific code in particular places. It is a rare instance where you will need these, but they are here if you need them:</p>
<ul>
<li><code>CEXCEPTION_HOOK_START_TRY</code> - called immediately before the Try block</li>
<li><code>CEXCEPTION_HOOK_HAPPY_TRY</code> - called immediately after the Try block if no exception was thrown</li>
<li><code>CEXCEPTION_HOOK_AFTER_TRY</code> - called immediately after the Try block OR before an exception is caught</li>
<li><code>CEXCEPTION_HOOK_START_CATCH</code> - called immediately before the catch</li>
</ul>
<h1><a class="anchor" id="autotoc_md54"></a>
Testing</h1>
<p >If you want to validate that CException works with your tools or that it works with your custom configuration, you may want to run the included test suite. This is the test suite (along with real projects we've used it on) that we use to make sure that things actually work the way we claim. The test suite makes use of Ceedling, which uses the Unity Test Framework. It will require a native C compiler. The example makefile and rakefile both use gcc.</p>
<h1><a class="anchor" id="autotoc_md55"></a>
License</h1>
<p ><em>This software is licensed under the MIT License: Copyright (c) 2007-2021 Mark VanderVoord</em></p>
<p ><em>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</em></p>
<p >*_THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE._* </p>
</div></div><!-- contents -->
</div><!-- PageDoc -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.4 </li>
  </ul>
</div>
</body>
</html>
