<map id="test_ThrowAndCatchFromASubFunctionAndRethrowToCatchInRootFunc" name="test_ThrowAndCatchFromASubFunctionAndRethrowToCatchInRootFunc">
<area shape="rect" id="Node000001" title=" " alt="" coords="5,5,264,46"/>
<area shape="rect" id="Node000002" href="$TestException_8c.html#a9e586145420288c4b36e1ccd96d350ce" title=" " alt="" coords="312,13,485,39"/>
<area shape="poly" id="edge1_Node000001_Node000002" title=" " alt="" coords="264,23,296,23,296,28,264,28"/>
<area shape="rect" id="Node000003" href="$CException_8c.html#a74995bac14be4f19ea95ed1ec9d510de" title=" " alt="" coords="533,13,590,39"/>
<area shape="poly" id="edge2_Node000002_Node000003" title=" " alt="" coords="486,23,517,23,517,28,486,28"/>
</map>
