<map id="test_ThrowFromASubFunctionAndCatchInRootFunc" name="test_ThrowFromASubFunctionAndCatchInRootFunc">
<area shape="rect" id="Node000001" title=" " alt="" coords="5,5,204,46"/>
<area shape="rect" id="Node000002" href="$TestException_8c.html#ae1827c0fd4a6d4b269d204b2e6a73bcc" title=" " alt="" coords="252,13,413,39"/>
<area shape="poly" id="edge1_Node000001_Node000002" title=" " alt="" coords="204,23,236,23,236,28,204,28"/>
<area shape="rect" id="Node000003" href="$CException_8c.html#a74995bac14be4f19ea95ed1ec9d510de" title=" " alt="" coords="461,13,518,39"/>
<area shape="poly" id="edge2_Node000002_Node000003" title=" " alt="" coords="413,23,445,23,445,28,413,28"/>
</map>
